# Generated by Django 4.2.8 on 2024-01-01 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_book_delete_astvoicemailusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoicemailUsers',
        ),
    ]
